import Link from "next/link"
import { ArrowRight, Boxes, Braces, Cable, Check, CircleStop, Code2, Database, Gauge, GitBranch, Layers3, Radio, Sparkles } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { MigrationTabs } from "@/components/site/migration-tabs"
import { OwnershipDemo } from "@/components/site/ownership-demo"

export type Locale = "ja" | "en" | "ko" | "zh"

const copy = {
  ja: {
    eyebrow: "TypeScript向け Request Ownership Runtime", titleA: "そのPromise、", titleB: "野放しにしない。", lead: "Neloは、リクエストから生まれたタスク・リソース・レスポンス配信を、最後まで同じリクエストに持たせます。RequestとResponseはWeb標準のままです。", primary: "使ってみる", secondary: "GitHubで見る", proof: ["Web Standards", "Explicit ownership", "Delivery aware"], valueEyebrow: "Neloが変えること", valueTitle: "終わるべき場所で、仕事を終わらせる。", valueLead: "機能を増やすより、寿命を曖昧にしない。Neloは非同期処理の開始・中断・後片付けを一つの所有モデルへまとめます。", migrateEyebrow: "小さく導入", migrateTitle: "ルートを書き直さず、所有者だけを足す。", migrateLead: "Task、Resource、Streamのどれか一つから始められます。", modelEyebrow: "Ownership model", modelTitle: "handler returnは、request endではない。", modelLead: "ハンドラ実行とレスポンス配信は別のタイミングで終わります。Neloは二つの寿命を分けて管理します。", runtimeEyebrow: "Runtime support", runtimeTitle: "動いたものだけ、動くと言う。", runtimeLead: "検証できていないアダプターを、対応済みとして並べません。", docsEyebrow: "Explore", docsTitle: "次に読むもの。"
  },
  en: {
    eyebrow: "Request ownership runtime for TypeScript", titleA: "Keep every promise", titleB: "inside the request.", lead: "Nelo keeps tasks, resources, and response delivery owned by the request that created them, while Request and Response stay standard.", primary: "Get started", secondary: "View on GitHub", proof: ["Web Standards", "Explicit ownership", "Delivery aware"], valueEyebrow: "What Nelo changes", valueTitle: "Work ends where it belongs.", valueLead: "Nelo brings start, cancellation, and cleanup into one ownership model instead of adding another layer of magic.", migrateEyebrow: "Adopt incrementally", migrateTitle: "Keep the route. Add the owner.", migrateLead: "Start with one task, resource, or stream.", modelEyebrow: "Ownership model", modelTitle: "Handler return is not request end.", modelLead: "Handler execution and response delivery finish at different times. Nelo owns both lifetimes explicitly.", runtimeEyebrow: "Runtime support", runtimeTitle: "Claims stop where verification stops.", runtimeLead: "An adapter is listed only after its actual transport behavior is tested.", docsEyebrow: "Explore", docsTitle: "Read next."
  },
  ko: {
    eyebrow: "TypeScript 요청 소유권 런타임", titleA: "Promise를", titleB: "요청 밖에 두지 마세요.", lead: "Nelo는 요청에서 시작된 작업, 리소스, 응답 전달을 끝까지 같은 요청이 소유하게 합니다. Request와 Response는 표준 그대로입니다.", primary: "시작하기", secondary: "GitHub 보기", proof: ["Web Standards", "Explicit ownership", "Delivery aware"], valueEyebrow: "Nelo가 바꾸는 것", valueTitle: "작업이 끝나야 할 곳에서 끝납니다.", valueLead: "비동기 작업의 시작, 취소, 정리를 하나의 소유권 모델로 묶습니다.", migrateEyebrow: "점진적 도입", migrateTitle: "라우트는 유지하고 소유자만 추가합니다.", migrateLead: "Task, Resource, Stream 중 하나부터 시작할 수 있습니다.", modelEyebrow: "Ownership model", modelTitle: "handler return은 request end가 아닙니다.", modelLead: "핸들러 실행과 응답 전달은 다른 시점에 끝납니다.", runtimeEyebrow: "Runtime support", runtimeTitle: "검증한 것만 지원한다고 말합니다.", runtimeLead: "실제 전송 동작을 확인한 어댑터만 표시합니다.", docsEyebrow: "Explore", docsTitle: "다음 문서."
  },
  zh: {
    eyebrow: "面向 TypeScript 的请求所有权运行时", titleA: "让每个 Promise", titleB: "都留在请求里。", lead: "Nelo 让任务、资源和响应传输始终由创建它们的请求负责，同时保持标准 Request 和 Response。", primary: "开始使用", secondary: "查看 GitHub", proof: ["Web Standards", "Explicit ownership", "Delivery aware"], valueEyebrow: "Nelo 改变什么", valueTitle: "让工作在该结束的地方结束。", valueLead: "把异步工作的启动、取消和清理放进同一个所有权模型。", migrateEyebrow: "渐进采用", migrateTitle: "保留路由，只增加所有者。", migrateLead: "可以从一个 Task、Resource 或 Stream 开始。", modelEyebrow: "Ownership model", modelTitle: "handler return 不等于 request end。", modelLead: "处理器执行和响应传输会在不同时间结束。", runtimeEyebrow: "Runtime support", runtimeTitle: "只声明经过验证的支持。", runtimeLead: "只有验证过真实传输行为的适配器才会列出。", docsEyebrow: "Explore", docsTitle: "继续阅读。"
  }
} satisfies Record<Locale, Record<string, string | string[]>>

const valueCards = [
  { icon: GitBranch, tag: "context.fork()", title: "Owned tasks", text: "A child task has a name, a parent, and a request signal. It cannot quietly outlive the request.", href: "/docs/concepts/request-ownership", className: "md:col-span-2" },
  { icon: Database, tag: "context.use()", title: "Cleanup once", text: "Acquisition and release stay together. Failure paths still clean up in LIFO order.", href: "/docs/concepts/request-ownership", className: "" },
  { icon: Radio, tag: "context.delivery", title: "Delivery is lifetime", text: "A resource remains alive until the response body is actually delivered, cancelled, or disconnected.", href: "/docs", className: "" },
  { icon: CircleStop, tag: "CancellationReason", title: "First reason wins", text: "One typed reason propagates through the tree without being overwritten by later failures.", href: "/docs", className: "md:col-span-2" }
]
const runtimes = [
  ["Portable core", "Available", "Fetch execution, ownership scopes, response-body tracking"],
  ["Node.js 20 / 22 / 24", "Adapter", "Real sockets, disconnects, backpressure, graceful shutdown"],
  ["Deno", "Core tested", "Portable execution; dedicated production adapter not shipped"],
  ["Cloudflare / Bun", "Planned", "No production adapter claim yet"]
]

export function HomePage({ locale = "ja" }: { locale?: Locale }) {
  const t = copy[locale]
  return <main>
    <section id="overview" className="relative overflow-hidden border-b border-white/6"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_18%_20%,rgba(56,127,255,.12),transparent_27%),radial-gradient(circle_at_78%_16%,rgba(96,211,185,.10),transparent_24%)]" /><div className="mx-auto grid min-h-[calc(100svh-4rem)] w-full max-w-7xl items-center gap-14 px-5 py-20 md:px-8 lg:grid-cols-[.94fr_1.06fr] lg:py-24"><div className="relative z-10"><Badge variant="outline" className="border-white/10 bg-white/[0.03] px-3 py-1.5 text-muted-foreground"><Sparkles className="size-3 text-emerald-300" />{t.eyebrow as string}</Badge><h1 className="mt-7 max-w-3xl text-balance text-[clamp(3.65rem,8vw,7.3rem)] font-semibold leading-[.88] tracking-[-.075em]">{t.titleA as string}<span className="block text-muted-foreground">{t.titleB as string}</span></h1><p className="mt-7 max-w-2xl text-pretty text-base leading-8 text-muted-foreground sm:text-lg">{t.lead as string}</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link href="/docs/getting-started">{t.primary as string}<ArrowRight /></Link></Button><Button size="lg" variant="outline" asChild><Link href="https://github.com/lasder-ca/Nelo">{t.secondary as string}</Link></Button></div><div className="mt-8 flex flex-wrap gap-2">{(t.proof as string[]).map((item) => <Badge key={item} variant="secondary" className="bg-white/[0.035] text-muted-foreground"><Check className="size-3 text-emerald-300" />{item}</Badge>)}</div></div><div className="relative z-10 lg:pl-4"><OwnershipDemo /></div></div></section>
    <section id="model" className="mx-auto w-full max-w-7xl px-5 py-24 md:px-8 md:py-32"><SectionHead eyebrow={t.valueEyebrow as string} title={t.valueTitle as string} lead={t.valueLead as string} /><div className="mt-12 grid gap-4 md:grid-cols-3">{valueCards.map((card) => <ValueCard key={card.title} {...card} />)}</div></section>
    <section id="migrate" className="border-y border-white/6 bg-white/[0.018]"><div className="mx-auto w-full max-w-7xl px-5 py-24 md:px-8 md:py-32"><SectionHead eyebrow={t.migrateEyebrow as string} title={t.migrateTitle as string} lead={t.migrateLead as string} /><div className="mt-12"><MigrationTabs /></div></div></section>
    <section className="mx-auto w-full max-w-7xl px-5 py-24 md:px-8 md:py-32"><SectionHead eyebrow={t.modelEyebrow as string} title={t.modelTitle as string} lead={t.modelLead as string} /><div className="mt-12 grid gap-4 lg:grid-cols-2"><LifetimeCard title="Handler lifetime" icon={Braces} items={["route code", "child tasks", "handler resources"]} accent="blue" /><LifetimeCard title="Delivery lifetime" icon={Cable} items={["response body", "stream producer", "disconnect cleanup"]} accent="mint" /></div></section>
    <section id="runtime" className="border-y border-white/6 bg-white/[0.018]"><div className="mx-auto w-full max-w-7xl px-5 py-24 md:px-8 md:py-32"><SectionHead eyebrow={t.runtimeEyebrow as string} title={t.runtimeTitle as string} lead={t.runtimeLead as string} /><Card className="mt-12 overflow-hidden p-0"><Table><TableHeader><TableRow><TableHead>Target</TableHead><TableHead>Status</TableHead><TableHead>Verified boundary</TableHead></TableRow></TableHeader><TableBody>{runtimes.map(([target, status, boundary]) => <TableRow key={target}><TableCell className="font-medium">{target}</TableCell><TableCell><Badge variant={status === "Planned" ? "outline" : "default"}>{status}</Badge></TableCell><TableCell className="min-w-[340px] text-muted-foreground">{boundary}</TableCell></TableRow>)}</TableBody></Table></Card></div></section>
    <section className="mx-auto w-full max-w-7xl px-5 py-24 md:px-8 md:py-32"><SectionHead eyebrow={t.docsEyebrow as string} title={t.docsTitle as string} lead="The site is now a navigation surface, not a wall of feature copy." /><div className="mt-12 grid gap-4 md:grid-cols-3"><ExploreCard icon={Code2} title="Getting started" text="Run one route and move its first task into the request." href="/docs/getting-started" /><ExploreCard icon={Layers3} title="Ownership model" text="Understand handler and delivery scopes before adding more code." href="/docs/concepts/request-ownership" /><ExploreCard icon={Boxes} title="Examples" text="See concrete task, resource, and streaming patterns." href="/examples" /></div></section>
    <section className="mx-auto w-full max-w-7xl px-5 pb-8 md:px-8"><Card className="relative overflow-hidden border-emerald-300/15 bg-emerald-300/[0.035] px-2 py-2"><CardContent className="grid items-center gap-8 p-8 md:grid-cols-[1fr_auto] md:p-12"><div><Badge variant="outline" className="border-emerald-300/20 text-emerald-300">Start small</Badge><h2 className="mt-5 text-3xl font-semibold tracking-tight md:text-5xl">Move one promise into the request.</h2><p className="mt-4 max-w-2xl text-muted-foreground">No custom Request type. No hidden global scheduler. Just one explicit owner.</p></div><Button size="lg" asChild><Link href="/docs/getting-started">Open the guide<ArrowRight /></Link></Button></CardContent></Card></section>
  </main>
}
function SectionHead({ eyebrow, title, lead }: { eyebrow: string; title: string; lead: string }) { return <div className="grid gap-7 lg:grid-cols-[.92fr_1.08fr] lg:items-end"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-emerald-300">{eyebrow}</p><h2 className="mt-4 text-balance text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-5xl md:text-6xl">{title}</h2></div><p className="max-w-2xl text-pretty text-base leading-8 text-muted-foreground md:text-lg">{lead}</p></div> }
function ValueCard({ icon: Icon, tag, title, text, href, className }: { icon: typeof Gauge; tag: string; title: string; text: string; href: string; className: string }) { return <Link href={href} className={className}><Card className="group h-full min-h-72 overflow-hidden transition duration-300 hover:-translate-y-1 hover:border-white/18 hover:bg-card"><CardHeader><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl border border-white/10 bg-white/[0.035] text-blue-300"><Icon className="size-5" /></span><Badge variant="outline" className="font-mono text-[10px]">{tag}</Badge></div></CardHeader><CardContent className="mt-auto"><CardTitle className="text-2xl tracking-tight">{title}</CardTitle><CardDescription className="mt-3 max-w-xl text-sm leading-7">{text}</CardDescription><span className="mt-7 inline-flex items-center gap-2 text-xs text-foreground">Read the model <ArrowRight className="size-3 transition-transform group-hover:translate-x-1" /></span></CardContent></Card></Link> }
function LifetimeCard({ title, icon: Icon, items, accent }: { title: string; icon: typeof Braces; items: string[]; accent: "blue" | "mint" }) { const isMint = accent === "mint"; return <Card className="overflow-hidden"><CardHeader><div className="flex items-center justify-between"><span className={`grid size-11 place-items-center rounded-xl border ${isMint ? "border-emerald-300/20 bg-emerald-300/5 text-emerald-300" : "border-blue-300/20 bg-blue-300/5 text-blue-300"}`}><Icon className="size-5" /></span><Badge variant="outline">scope</Badge></div><CardTitle className="mt-6 text-2xl">{title}</CardTitle></CardHeader><CardContent><div className="grid gap-2">{items.map((item, index) => <div key={item} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[0.025] px-4 py-3"><span className="text-sm">{item}</span><span className={`font-mono text-[10px] ${isMint ? "text-emerald-300" : "text-blue-300"}`}>0{index + 1}</span></div>)}</div></CardContent></Card> }
function ExploreCard({ icon: Icon, title, text, href }: { icon: typeof Code2; title: string; text: string; href: string }) { return <Link href={href}><Card className="group h-full min-h-60 transition duration-300 hover:-translate-y-1 hover:border-white/18"><CardHeader><Icon className="size-5 text-emerald-300" /><CardTitle className="mt-7 text-2xl">{title}</CardTitle><CardDescription className="mt-2 leading-7">{text}</CardDescription></CardHeader><div className="mt-auto flex items-center gap-2 px-6 text-xs text-muted-foreground">Open <ArrowRight className="size-3 transition-transform group-hover:translate-x-1" /></div></Card></Link> }
