"use client";

import { CheckCircle2, Circle, Loader2, Play, XCircle } from "lucide-react";
import { useState } from "react";

type Scenario = "success" | "disconnect" | "failure";
type Event = { phase: "handler" | "delivery"; label: string; status: "complete" | "cancelled" | "failed"; at: number };
type Result = { requestId: string; scenario: Scenario; outcome: "completed" | "aborted" | "failed"; duration: number; events: Event[] };

const scenarios: Array<{ id: Scenario; label: string }> = [
  { id: "success", label: "Complete" },
  { id: "disconnect", label: "Disconnect" },
  { id: "failure", label: "Producer error" },
];

export function RequestLab() {
  const [scenario, setScenario] = useState<Scenario>("success");
  const [result, setResult] = useState<Result | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function run() {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch("/api/lifecycle", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ scenario }),
      });
      if (!response.ok) throw new Error("The lifecycle run failed.");
      setResult((await response.json()) as Result);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "The lifecycle run failed.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="request-lab">
      <div className="request-lab-toolbar">
        <div className="scenario-tabs">
          {scenarios.map((item) => (
            <button
              key={item.id}
              type="button"
              className={scenario === item.id ? "active" : ""}
              onClick={() => setScenario(item.id)}
            >
              {item.label}
            </button>
          ))}
        </div>
        <button type="button" className="primary-button run-button" onClick={run} disabled={loading}>
          {loading ? <Loader2 size={14} className="animate-spin" /> : <Play size={14} />}
          Run request
        </button>
      </div>

      <div className="request-lab-body">
        <div className="request-meta">
          <span>POST /api/lifecycle</span>
          <span>{result ? `${result.outcome} · ${result.duration}ms` : "waiting"}</span>
        </div>

        {result ? (
          <div>
            <p className="request-id">request / {result.requestId}</p>
            <ol className="timeline">
              {result.events.map((event, index) => (
                <li key={`${event.label}-${index}`}>
                  <span className="timeline-icon">
                    {event.status === "complete" ? <CheckCircle2 size={15} /> : event.status === "failed" ? <XCircle size={15} /> : <Circle size={15} />}
                  </span>
                  <span className="timeline-label"><strong>{event.label}</strong><small>{event.phase} scope</small></span>
                  <code>+{event.at}ms</code>
                </li>
              ))}
            </ol>
          </div>
        ) : (
          <div className="request-empty">
            <p>Select a scenario and run the request.</p>
            <span>The response is generated by the server route, not mocked in the browser.</span>
          </div>
        )}
        {error ? <p className="request-error">{error}</p> : null}
      </div>
    </div>
  );
}
